# Generated by Django 5.2.17 on 2026-09-02 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('sigla', models.CharField(max_length=3)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=2)),
                ('cor_primaria', models.CharField(default='#111827', max_length=7)),
                ('cor_secundaria', models.CharField(default='#ffffff', max_length=7)),
                ('escudo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do time')),
                ('torcedor', models.CharField(blank=True, max_length=60, verbose_name='Cartoleiro')),
                ('formacao', models.CharField(choices=[('3-4-3', '3-4-3'), ('3-5-2', '3-5-2'), ('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], default='4-3-3', max_length=10, verbose_name='Formação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escalação',
                'verbose_name_plural': 'Escalações',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do jogador')),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('MEI', 'Meia'), ('ATA', 'Atacante')], max_length=3, verbose_name='Posição')),
                ('numero', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Número da camisa')),
                ('gols', models.PositiveIntegerField(default=0, verbose_name='Gols')),
                ('assistencias', models.PositiveIntegerField(default=0, verbose_name='Assistências')),
                ('posse_bola', models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Posse de bola (%)')),
                ('foto', models.URLField(blank=True, help_text='Cole o endereço de uma imagem. Sem foto, usamos o escudo do clube.', max_length=400, verbose_name='Foto do jogador (URL)')),
                ('capitao', models.BooleanField(default=False, verbose_name='Capitão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogadores', to='futebol.clube', verbose_name='Clube')),
                ('escalacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='futebol.escalacao')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['posicao', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('resumo', models.TextField(max_length=400, verbose_name='Resumo')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='futebol.jogador')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao', '-id'],
            },
        ),
    ]
