# Generated by Django 5.2.17 on 2026-09-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID na API Futebol')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('MEI', 'Meia'), ('ATA', 'Atacante')], max_length=3, verbose_name='Posição')),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Camisa')),
                ('gols', models.PositiveIntegerField(default=0, verbose_name='Gols')),
                ('fonte', models.CharField(choices=[('local', 'Catálogo local'), ('artilharia', 'Artilharia (API Futebol)'), ('escalacao', 'Escalação de partida (API Futebol)')], default='local', max_length=20, verbose_name='Origem')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='futebol.clube', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Atleta do catálogo',
                'verbose_name_plural': 'Catálogo de atletas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'clube'), name='catalogo_nome_clube_unico')],
            },
        ),
    ]
