# Generated by Django 5.2.17 on 2026-09-02 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0002_atleta_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletacatalogo',
            name='fonte_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID no provider de assets'),
        ),
        migrations.AddField(
            model_name='atletacatalogo',
            name='foto_fonte',
            field=models.CharField(blank=True, max_length=40, verbose_name='Fonte da foto'),
        ),
        migrations.AddField(
            model_name='atletacatalogo',
            name='foto_local',
            field=models.CharField(blank=True, max_length=300, verbose_name='Foto local'),
        ),
        migrations.AddField(
            model_name='atletacatalogo',
            name='foto_status',
            field=models.CharField(choices=[('ok', 'OK'), ('missing', 'MISSING'), ('invalid', 'INVALID'), ('fallback', 'FALLBACK')], default='missing', max_length=12, verbose_name='Status da foto'),
        ),
        migrations.AddField(
            model_name='atletacatalogo',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL da foto'),
        ),
        migrations.AddField(
            model_name='atletacatalogo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clube',
            name='fonte_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID no provider'),
        ),
        migrations.AddField(
            model_name='clube',
            name='logo_fonte',
            field=models.CharField(blank=True, max_length=40, verbose_name='Fonte do escudo'),
        ),
        migrations.AddField(
            model_name='clube',
            name='logo_local',
            field=models.CharField(blank=True, max_length=300, verbose_name='Escudo local'),
        ),
        migrations.AddField(
            model_name='clube',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL do escudo'),
        ),
        migrations.AddField(
            model_name='clube',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='atletacatalogo',
            name='fonte',
            field=models.CharField(choices=[('local', 'Catálogo local'), ('cartola', 'Cartola FC'), ('artilharia', 'Artilharia (API Futebol)'), ('escalacao', 'Escalação de partida (API Futebol)')], default='local', max_length=20, verbose_name='Origem'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('team', 'Clube'), ('player', 'Jogador')], max_length=12)),
                ('entity_id', models.PositiveIntegerField()),
                ('asset_type', models.CharField(choices=[('logo', 'Escudo'), ('photo', 'Foto')], max_length=12)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=300)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('mime', models.CharField(blank=True, max_length=60)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('missing', 'MISSING'), ('invalid', 'INVALID'), ('fallback', 'FALLBACK'), ('error', 'ERROR')], default='missing', max_length=12)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['entity_type', 'entity_id'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'asset_type'), name='asset_entidade_tipo_unico')],
            },
        ),
    ]
